version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - ./app:/home/seluser/Downloads
    ports:
    - 4444:4444
    restart: always
    shm_size: '2gb'

  app:
    build:
      context: .
    volumes:
      - ./app:/app
    command: sh -c "uvicorn selenium_script:app  --host 0.0.0.0 --reload"
    ports:
    - 8000:8000
    depends_on:
      - selenium
    restart: on-failure
